from enum import Enum

class Cores(Enum):
    ROXO = '\033[95m'
    AZUL = '\033[94m'
    CIANO = '\033[96m'
    VERDE = '\033[92m'
    AMARELO = '\033[93m'
    VERMELHO = '\033[91m'
    LARANJA = '\033[38;5;208m'
    MAGENTA = '\033[35m'
    CASTANHO = '\033[38;5;130m'
    CINZA = '\033[90m'
    NORMAL = '\033[0m'
    NEGRITO = '\033[1m'

    def __str__(self):
        return self.value
    
class Mensagem(Enum):
    SUCESSO = 1
    ERRO_GENERICO = 2
    UTILIZADOR_CRIADO = 4
    UTILIZADOR_JA_EXISTE = 5
    LOGIN_INVALIDO = 6
    CREDENCIAIS_INVALIDAS = 7
    PERMISSAO_NEGADA = 8
    O_PERFIL_JA_E_ADMIN = 9
    O_VENDEDOR_TEM_QUE_SER_ASSOCIADO_A_LOJA = 10
    CARGO_INVALIDO = 11
    REGISTRO_INDISPONIVEL = 12
    LOJA_NAO_ENCONTRADA = 13
    COMANDO_DESCONHECIDO = 14
    ADICIONADO = 15
    ERRO_DUPLICADO = 16
    ATUALIZADO = 17
    NAO_ENCONTRADO = 18
    REMOVIDO = 19
    ERRO_LOJA_OBRIGATORIA = 20
    ERRO_PERMISSAO = 21
    PENDENTE = 22
    CONFIRMADA = 23
    CONCLUIDA = 24
    STOCK_INSUFICIENTE = 25
    PRODUTO_NAO_ENCONTRADO = 26
    ERRO_PROCESSAMENTO = 27
    ALERTA_STOCK_BAIXO = 28
    
    def __str__(self):
        return self.name