from enum import Enum

class Mensagem(Enum):
    SUCESSO = 1
    ERRO_GENERICO = 2
    UTILIZADOR_CRIADO = 4
    UTILIZADOR_JA_EXISTE = 5
    LOGIN_INVALIDO = 6
    CREDENCIAIS_INVALIDAS = 7
    PERMISSAO_NEGADA = 8
    O_PERFIL_JA_E_ADMIN = 9
    O_VENDEDOR_TEM_QUE_SER_ASSOCIADO_A_LOJA = 10
    CARGO_INVALIDO = 11
    REGISTRO_INDISPONIVEL = 12
    LOJA_NAO_ENCONTRADA = 13
    COMANDO_DESCONHECIDO = 14
    ADICIONADO = 1
    ERRO_DUPLICADO = 2
    ATUALIZADO = 3
    NAO_ENCONTRADO = 4
    REMOVIDO = 5
    ERRO_LOJA_OBRIGATORIA = 6 
    ERRO_PERMISSAO = 7
    PENDENTE = 1
    CONFIRMADA = 2
    CONCLUIDA = 3
    STOCK_INSUFICIENTE = 4
    PRODUTO_NAO_ENCONTRADO = 5
    ERRO_PROCESSAMENTO = 6