class Gestão_Vendas():
    def __init__(self, ):
        ...

#REGISTRO DE VENDAS(CLIENTE)
    def escolher_Produto(): #ESCOLHE OS PRODUTOS QUE DESEJA COMPRAR JUNTAMENTE COM A QUANTIDADE DE CADA PRODUTO, DEVE TAMBEM TER COMO MUDAR A QUANTIDADE E REMOVER UM PRODUTO INDESEJADO DA LISTA DE COMPRAS.
        ...

    def confirmar_Compra(self): #PERGUNTA SE DESEJA FINALIZAR A COMPRA E MOSTRAR O PREÇO TOTAL DA COMPRA.
        ...

    def enviar_Pedido_Venda(): # ISSO VAI ENVIAR AO SERVIDOR O PEDIDO DE VENDA, NO CASO VAI RETIRAR A QUANTIDADE PEDIDA QUE ESTAVA NO STOCK DE CADA PRODUTO APÓS A VENDA DOS PRODUTOS.
        ...

#HISTORICO DE VENDAS(VENDEDOR)
    def consultar_Historico(self): #MOSTRAR A LISTA DE VENDAS DO VENDEDOR.
        ...