class ConfiguracaoServidor:
    ENDERECO_PADRAO = '127.0.0.1'
    PORTA_PADRAO = 5000
    MODO_DEPURACAO: bool = False
    CHAVE_SECRETA_ADMIN = "ESTA_SENHA_É_USADA_NA_CRIAÇÃO_DE_NOVOS_ADMIN_PROVAVELMENTE_SERÁ_REMOVIDA_DEPOIS__POIS_ESTA_SENHA_É_MUITO_GRANDE!_OK?"
